### ISSUE TITLE
release 0.1.0

### ISSUE THREAD

**Issue by theskumar** [pydelhi/mailing-list-guidelines#1]
Goal: Have a basic guidelines up ready for reference.

---
- [x] add guides as per the issue (https://github.com/pydelhi/pydelhi.github.io/issues/6)
- [x] add/update basic styles
- [x] add link to this guide on pydelhi.org

**Comment by satyaakam** [comment]
https://dpaste.de/Q0CG/raw

**Comment by satyaakam** [comment]
We can close this one as release 0.1.0 is out.
